require:
  - rubocop-rails
  - rubocop-rspec

Bundler/OrderedGems:
  Enabled: true
  
Style/Documentation:
  Enabled: false
  
Style/EmptyMethod:
  Enabled: false
  
Style/Lambda:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
  
Style/EmptyCaseCondition:
  Enabled: false
  
Style/HashEachMethods:
  Enabled: true
  
Style/HashTransformKeys:
  Enabled: true
  
Style/HashTransformValues:
  Enabled: true
  
Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific
  
Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Style/NamedSubject:
  Enabled: false

Rails/FilePath:
  Exclude: 
    - 'spec/factories/**/*'
  
Metrics/AbcSize:
  Max: 25
  
Metrics/MethodLength:
  Max: 15
  
Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9
  
Lint/SuppressedException:
  Enabled: false
  
Lint/AmbiguousBlockAssociation:
  Enabled: true
  
  Exclude:
    - 'spec/**/*'
    
Lint/RaiseException:
  Enabled: true
  
Layout/LineLength:
  Max: 82
  IgnoredPatterns: ['\A#']
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'
    - 'config/environments/test.rb'
    - 'bin/bundle'
  
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
  
Lint/StructNewOverride:
  Enabled: true
  
RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*'
    
RSpec/NestedGroups:
  Max: 6
  
AllCops:
  Exclude:
    - 'bundle/**/*'
    - '.bundle/**/*'
    - 'bin/setup'
    - 'bin/yarn'
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
